//mod print;
//mod vars;
//mod types;
//mod strings;
//mod tuples;
//mod arrays;
//mod vectors;
//mod conditionals;
//mod loops;
//mod functions;
//mod pointer_ref;
mod structs;
mod ownership_example;
//mod enums;
//mod cli;
fn main() {
//print::run();
//vars::run();
//types::run();
//strings::run();
//tuples::run();
//arrays::run();
//vectors::run();
//conditionals::run();
//loops::run();
//functions::run();
//pointer_ref::run();
structs::run();
ownership_example::run();
//enums::run();
//cli::run();
}
