//mod arrays;
mod asynchronus;
//mod error_handling;
//mod print;
//mod vars;
//mod types;
//mod strings;
//mod tuples;
//mod generics;
//mod vectors;
//mod conditionals;
//mod hashmap;
//mod iterators;
//mod lifetimes;
//mod loops;
//mod optionals;
//mod functions;
//mod pointer_ref;
//mod pointer;
//mod structs;
//mod ownership_example;
//mod enums;
//mod cli;
//mod traits;
fn main() {
    //arrays::run();
    asynchronus::run();
//print::run();
//vars::run();
//types::run();
//strings::run();
//tuples::run();
//generics :: run();
//vectors::run();
//conditionals::run();
//hashmap::run();
//iterators::run();
//lifetimes::run();
//loops::run();
//optionals::run();
//functions::run();
//pointer_ref::run();
//pointer::run();
//structs::run();
//ownership_example::run();
//enums::run();
//cli::run();
//error_handling::run();
//traits::run();
}
